name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for Creating the issue, we will get back to you within 24 Hours'
        pr-message: 'Hey Congratulations for creating your 1st PR, one green square of a day'
